import pytest
from unittest.mock import patch, MagicMock
from datetime import datetime
from noteflow.email_sender import EmailSender

@pytest.fixture
def dummy_notes():
    return {
        "summary": "We discussed the new product launch.",
        "action_items": [
            {"owner": "Alice", "action": "Prepare slides", "deadline": "Friday"},
            {"owner": "Bob", "action": "Review budget", "deadline": "Monday"}
        ],
        "highlights": ["Great quarterly results", "New client acquired"],
        "decisions": ["Approved $10k budget for marketing"]
    }

@pytest.fixture
def email_sender(tmp_path):
    # Patch the template path to point to a temporary file
    template = "<html><title>{title}</title><body>Duration: {duration} Details: <details><summary>Transcript</summary>{transcript}</details> Actions: {action_items_html} </body></html>"
    
    sender = EmailSender(
        host="smtp.example.com",
        port=587,
        use_tls=True,
        username="user",
        password="password",
        email_from="from@example.com",
        email_to="to@example.com"
    )
    sender.html_template = template
    return sender

def test_html_contains_meeting_title(email_sender, dummy_notes):
    html = email_sender.build_html(
        notes=dummy_notes,
        title="Project Kickoff",
        duration="1h",
        start_time="10:00",
        end_time="11:00",
        transcript="Hello, welcome to the kickoff.",
        date_str="2023-01-01"
    )
    assert "Project Kickoff" in html

def test_html_contains_duration(email_sender, dummy_notes):
    html = email_sender.build_html(
        notes=dummy_notes,
        title="Project Kickoff",
        duration="45m",
        start_time="10:00",
        end_time="10:45",
        transcript="Hello",
        date_str="2023-01-01"
    )
    assert "Duration: 45m" in html

def test_html_contains_action_items_table(email_sender, dummy_notes):
    html = email_sender.build_html(
        notes=dummy_notes,
        title="Project Kickoff",
        duration="1h",
        start_time="10:00",
        end_time="11:00",
        transcript="Hello",
        date_str="2023-01-01"
    )
    assert "Alice" in html
    assert "Prepare slides" in html
    assert "Bob" in html

def test_html_contains_transcript_in_details_tag(email_sender, dummy_notes):
    html = email_sender.build_html(
        notes=dummy_notes,
        title="Project Kickoff",
        duration="1h",
        start_time="10:00",
        end_time="11:00",
        transcript="This is the raw transcript text.",
        date_str="2023-01-01"
    )
    assert "<details>" in html
    assert "This is the raw transcript text." in html

def test_plain_text_contains_all_sections(email_sender, dummy_notes):
    text = email_sender.build_plain_text(
        notes=dummy_notes,
        title="Plain Text Test",
        duration="30m",
        start_time="10:00",
        end_time="10:30",
        transcript="This is plain text transcript.",
        date_str="2023-01-01"
    )
    assert "Meeting: Plain Text Test" in text
    assert "SUMMARY" in text
    assert "We discussed the new product launch." in text
    assert "ACTION ITEMS" in text
    assert "[Alice] Prepare slides (Due: Friday)" in text
    assert "HIGHLIGHTS" in text
    assert "- Great quarterly results" in text
    assert "DECISIONS" in text
    assert "- Approved $10k budget for marketing" in text
    assert "RAW TRANSCRIPT" in text
    assert "This is plain text transcript." in text
    assert "Generated by NoteFlow" in text

@patch("smtplib.SMTP")
def test_send_uses_starttls_for_port_587(mock_smtp, email_sender, dummy_notes):
    mock_server = MagicMock()
    mock_smtp.return_value = mock_server

    email_sender.send(
        notes=dummy_notes,
        title="Test StartTLS",
        duration="1h",
        start_time="10:00",
        end_time="11:00",
        transcript="Testing StartTLS"
    )

    mock_smtp.assert_called_once_with("smtp.example.com", 587)
    mock_server.starttls.assert_called_once()
    mock_server.login.assert_called_once_with("user", "password")
    mock_server.sendmail.assert_called_once()
    mock_server.quit.assert_called_once()

@patch("smtplib.SMTP_SSL")
def test_send_uses_ssl_for_port_465(mock_smtp_ssl, dummy_notes):
    sender = EmailSender(
        host="smtp.example.com",
        port=465,
        use_tls=False,
        username="user",
        password="password",
        email_from="from@example.com",
        email_to="to@example.com"
    )
    
    mock_server = MagicMock()
    mock_smtp_ssl.return_value = mock_server

    sender.send(
        notes=dummy_notes,
        title="Test SSL",
        duration="1h",
        start_time="10:00",
        end_time="11:00",
        transcript="Testing SSL"
    )

    mock_smtp_ssl.assert_called_once_with("smtp.example.com", 465)
    mock_server.starttls.assert_not_called()
    mock_server.login.assert_called_once_with("user", "password")
    mock_server.sendmail.assert_called_once()
    mock_server.quit.assert_called_once()

@patch("smtplib.SMTP")
def test_smtp_auth_failure_raises(mock_smtp, email_sender, dummy_notes):
    import smtplib
    mock_server = MagicMock()
    mock_server.login.side_effect = smtplib.SMTPAuthenticationError(535, b"Auth failed")
    mock_smtp.return_value = mock_server

    with pytest.raises(smtplib.SMTPAuthenticationError):
        email_sender.send(
            notes=dummy_notes,
            title="Test Auth Failure",
            duration="1h",
            start_time="10:00",
            end_time="11:00",
            transcript="Fail"
        )
    mock_server.quit.assert_called_once()

@patch("smtplib.SMTP")
def test_subject_contains_prefix_and_title(mock_smtp, email_sender, dummy_notes):
    mock_server = MagicMock()
    mock_smtp.return_value = mock_server
    
    email_sender.send(
        notes=dummy_notes,
        title="Important Meeting",
        duration="1h",
        start_time="10:00",
        end_time="11:00",
        transcript="Subject test"
    )
    
    # Check the msg as string passed to sendmail
    call_args = mock_server.sendmail.call_args[0]
    msg_string = call_args[2]
    
    assert "[NoteFlow] Important Meeting" in msg_string
    assert "Subject: [NoteFlow] Important Meeting" in msg_string
